-- maze_player.lua  (GENERATED by gen_maze.py, seed 1337)
-- First-person maze: WASD move, mouse-look, Tab toggles cursor, reach the
-- gold crystal to win. Walls are baked in scenes/maze.lscene from the SAME
-- grid below, so collision here matches the geometry exactly.

local CELL = 3.0
local W, H = 17, 17
local RADIUS = 0.9          -- player collision radius (world units)
local speed = 6.0
local sensitivity = 0.12
local KEY_TAB = 258

-- grid[r] is a 1-based string of length W; '#' = wall, '.' = floor
local grid = {
        "#################",
        "#.#...........#.#",
        "#.#######.#.#.#.#",
        "#.......#.#.#...#",
        "#######.###.###.#",
        "#.#.....#...#.#.#",
        "#.#.#####.###.#.#",
        "#.#.#...#.#.....#",
        "#.#.#.#.#.#######",
        "#.#.#.#...#.....#",
        "#.#.#.#####.###.#",
        "#...#.........#.#",
        "#.#######.#####.#",
        "#.......#...#...#",
        "#######.#####.#.#",
        "#.............#.#",
        "#################"
}

local goal_c, goal_r = 16, 16  -- 1-based grid coords

local M = {}
local tabWasDown = false
local won = false

-- world (x,z) -> grid is a wall?
local function is_wall(wx, wz)
    local c = math.floor(wx / CELL + (W - 1) / 2.0 + 0.5)
    local r = math.floor(wz / CELL + (H - 1) / 2.0 + 0.5)
    if c < 0 or c >= W or r < 0 or r >= H then return true end
    local row = grid[r + 1]                       -- Lua 1-based
    return row:sub(c + 1, c + 1) == "#"
end

-- can the player circle stand at (wx,wz)? sample 4 offsets by RADIUS
local function blocked(wx, wz)
    return is_wall(wx + RADIUS, wz) or is_wall(wx - RADIUS, wz)
        or is_wall(wx, wz + RADIUS) or is_wall(wx, wz - RADIUS)
end

function M.on_start(self)
    lm.input.set_cursor_captured(true)
    lm.log("maze: reach the gold crystal. WASD + mouse, Tab frees cursor.")
end

function M.on_update(self, dt)
    local t = self:get_transform()

    local tabDown = lm.input.key_down(KEY_TAB)
    if tabDown and not tabWasDown then
        lm.input.set_cursor_captured(not lm.input.cursor_captured())
    end
    tabWasDown = tabDown

    if lm.input.cursor_captured() then
        local dx, dy = lm.input.mouse_delta()
        t.rotation.y = t.rotation.y - dx * sensitivity
        local pitch = t.rotation.x - dy * sensitivity
        if pitch > 89.0 then pitch = 89.0 end
        if pitch < -89.0 then pitch = -89.0 end
        t.rotation.x = pitch
    end

    local yaw = math.rad(t.rotation.y)
    local fx, fz = -math.sin(yaw), -math.cos(yaw)
    local rx, rz = math.cos(yaw), -math.sin(yaw)

    local mx, mz = 0.0, 0.0
    if lm.input.key_down("w") then mx = mx + fx; mz = mz + fz end
    if lm.input.key_down("s") then mx = mx - fx; mz = mz - fz end
    if lm.input.key_down("d") then mx = mx + rx; mz = mz + rz end
    if lm.input.key_down("a") then mx = mx - rx; mz = mz - rz end

    local len = math.sqrt(mx * mx + mz * mz)
    if len > 0.0 then
        local step = speed * dt / len
        local nx = t.position.x + mx * step
        local nz = t.position.z + mz * step
        -- axis-separated so we slide along walls instead of sticking
        if not blocked(nx, t.position.z) then t.position.x = nx end
        if not blocked(t.position.x, nz) then t.position.z = nz end
    end

    if not won then
        local gx = (goal_c - 1 - (W - 1) / 2.0) * CELL
        local gz = (goal_r - 1 - (H - 1) / 2.0) * CELL
        local ddx, ddz = t.position.x - gx, t.position.z - gz
        if (ddx * ddx + ddz * ddz) < (CELL * 0.7) ^ 2 then
            won = true
            lm.log("YOU ESCAPED THE MAZE!")
            lm.audio.event("jump")
        end
    end
end

return M
