#pragma once
// ComponentRegistry: the one table that knows every serializable/inspectable
// component type. Scene save/load iterates it; the Phase 6 editor will walk it
// to draw inspectors; Phase 5 hangs Lua bindings off it. Registering a type
// means providing a stable name plus to/from JSON; everything entt-facing is
// generated by the registerComponent<T> template.
//
//   ComponentRegistry::instance().registerComponent<MyThing>(
//       "MyThing",
//       [](const MyThing& c) { return nlohmann::json{{"x", c.x}}; },
//       [](MyThing& c, const nlohmann::json& j) { j.at("x").get_to(c.x); });
//
// Built-ins (Name, Transform, MeshRenderer, Camera, AudioSource, Light,
// Script) are registered by registerBuiltinComponents(), which Scene
// serialization and App call lazily — apps only call it themselves if they
// touch the registry before either.

#include <functional>
#include <string>
#include <vector>

#include <entt/entt.hpp>
#include <nlohmann/json.hpp>

namespace liminal {

struct ComponentOps {
    std::string name;

    // entt plumbing, generated by registerComponent<T>.
    std::function<bool(const entt::registry&, entt::entity)> has;
    std::function<nlohmann::json(const entt::registry&, entt::entity)> toJson;
    std::function<void(entt::registry&, entt::entity, const nlohmann::json&)> fromJson;
    std::function<void(entt::registry&, entt::entity)> removeFrom;
    // Mutable pointer to the component on this entity (nullptr if absent) —
    // what the editor feeds to inspectorDraw.
    std::function<void*(entt::registry&, entt::entity)> getRaw;

    // Draws ImGui widgets for one component instance. `component` is the T*
    // from getRaw. Null = no inspector (Phase 6 editor shows name only).
    std::function<void(void* component)> inspectorDraw;

    // Phase 5 placeholder: binds the component type into a Lua state. The
    // void* will be the sol::state*; typed wiring lands with scripting.
    void (*luaBind)(void* luaState) = nullptr;
};

class ComponentRegistry {
public:
    static ComponentRegistry& instance();

    // Registers T under `name`. The serializer pair works on typed
    // references; entt glue is generated here. Re-registering a name
    // overwrites its ops (idempotent for the built-ins).
    template <typename T>
    void registerComponent(const std::string& name,
                           std::function<nlohmann::json(const T&)> toJson,
                           std::function<void(T&, const nlohmann::json&)> fromJson,
                           std::function<void(T&)> inspectorDraw = nullptr,
                           void (*luaBind)(void*) = nullptr) {
        ComponentOps ops;
        ops.name = name;
        ops.has = [](const entt::registry& r, entt::entity e) {
            return r.all_of<T>(e);
        };
        ops.toJson = [toJson](const entt::registry& r, entt::entity e) {
            return toJson(r.get<T>(e));
        };
        ops.fromJson = [fromJson](entt::registry& r, entt::entity e,
                                  const nlohmann::json& j) {
            T c{};
            fromJson(c, j);
            r.emplace_or_replace<T>(e, std::move(c));
        };
        ops.removeFrom = [](entt::registry& r, entt::entity e) { r.remove<T>(e); };
        ops.getRaw = [](entt::registry& r, entt::entity e) -> void* {
            return r.try_get<T>(e);
        };
        if (inspectorDraw) {
            ops.inspectorDraw = [inspectorDraw](void* c) {
                inspectorDraw(*static_cast<T*>(c));
            };
        }
        ops.luaBind = luaBind;
        registerOps(std::move(ops));
    }

    // Lookup by stable name; nullptr if unknown.
    const ComponentOps* find(const std::string& name) const;

    // Registration order — what serialization iterates.
    const std::vector<ComponentOps>& all() const { return m_ops; }

private:
    void registerOps(ComponentOps ops);
    std::vector<ComponentOps> m_ops;
};

// Registers the built-in components (with inspectors). Safe to call more than
// once; only the first call does work.
void registerBuiltinComponents();

} // namespace liminal
